version: '3'
services:
    isa-poemsAPP-db:
      image: mariadb:10.4.4
      container_name: isa-poemsAPP-db-dev
      restart: unless-stopped
      environment:
        - MYSQL_USER=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=poemsAPP
      command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default_time_zone=-03:00 --net-read-timeout=60 --net-write-timeout=120 --max-allowed-packet=536870912 --wait-timeout=1850 --interactive-timeout=1850
      networks:
        - isa-poemsAPP-backend-dev
      volumes:
        - mariadb-isa-poemsAPP:/var/lib/mysql

    isa-poemsAPP-backend:
      image: jhipster/jhipster
      container_name: isa-poemsAPP-backend-dev
      restart: unless-stopped
      depends_on:
        - isa-poemsAPP-db
      ports:
        - '8080:8080'
        - '9000:9000'
        - '3001:3001'
      networks:
        - isa-poemsAPP-backend-dev
      volumes:
        - ~/Facultad/Ingenieria-Software-Aplicada/Final-ISA-PoemsAPP:/home/jhipster/app
        - ~/Facultad/Ingenieria-Software-Aplicada/Final-ISA-PoemsAPP/.m2:/home/jhipster/.m2

networks:
  isa-poemsAPP-backend-dev:
    driver: 'bridge'

volumes:
  mariadb-isa-poemsAPP:
